### ISSUE TITLE
Redirect completion to sub-process

### ISSUE THREAD

**Issue by frankcarey** [devinci-code/ahoy#20]
It would be awesome if bash-completion could be redirected down into the subprocess.

Example command:
```Yaml
commands:
  complete:
    cmd: git
```

When I type `ahoy complete <TAB>`, I get nothing (process hangs because the current setup is actually calling the 'git' command instead of forwarding the <tab> to it.
