### ISSUE TITLE
Quotes are lost when running ahoy commands from other ahoy commands

### ISSUE THREAD

**Issue by frankcarey** [devinci-code/ahoy#7]
It's pretty handy to call other ahoy commands (almost like reusable functions). This works pretty well most of the time, but if your "sub-command" uses quotes, they can get lost on the second call it seems. 

Issue seems to be how Yaml handles the quotes. If you want to use quotes, then you have to not wrap the whole thing in the same quote. 

### Example 
```Yaml
...
  commands:
    echo-success:
      cmd: echo "{{args}}"
    echo-fail:
      cmd: "echo {{args}}"
    echo-test:
      cmd: ahoy echo-success "'quotes'" && ahoy echo-fail "'quotes'"
```

```
$ ahoy echo-test test
2015/12/01 19:18:13 run command:  ahoy echo-success "'quotes'" && ahoy echo-fail "'quotes'"
2015/12/01 19:18:13 run command:  echo "'quotes'"
'quotes'
2015/12/01 19:18:13 run command:  echo 'quotes'
quotes
```
